In [1]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [3]:
import numpy as np

In [5]:
np.mean(revenus)

2134.4

In [7]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [9]:
revenus_array = np.array(revenus)
revenus_array
# array([1800, 1500, 2200, 3000, 2172])


array([1800, 1500, 2200, 3000, 2172])

In [11]:
revenus_array.dtype
# dtype('int32')

dtype('int64')

In [13]:
# pour accéder au 5ème élement
revenus_array[4]


2172

In [15]:
# pour accéder au dernier élément
revenus_array[-1]


2172

In [17]:
revenus_array[0:3]

array([1800, 1500, 2200])

In [19]:
# Les 3 premiers éléments
print(revenus_array[:3])


[1800 1500 2200]


In [21]:
# Les éléments à partir de l’indice 2
print(revenus_array[2:])


[2200 3000 2172]


In [23]:
# Un élément sur deux
print(revenus_array[::2])

[1800 2200 2172]


In [25]:
revenus_array[::-1]

array([2172, 3000, 2200, 1500, 1800])

In [27]:
revenus_array[revenus_array > 2000]
# array([2200, 3000, 2172])

array([2200, 3000, 2172])

In [29]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]
# array([2200, 2172])

array([2200, 2172])

In [31]:
revenus_array.shape


(5,)

In [33]:
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()

1500

In [35]:
revenus_array.max()


3000

In [37]:
#exercice
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

In [39]:
#créez un array que vous nommerez revenus :

In [41]:
revenus = np.array(liste)

In [47]:
revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

In [55]:
#créez un nouvel array haut_revenus dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€ 
haut_revenus = [revenus >=3000]
haut_revenus

[array([False, False, False,  True, False,  True, False, False, False,
        False])]

In [57]:
haut_revenus = revenus[revenus>=3000]

In [59]:
haut_revenus

array([3000, 5000])

In [83]:
#calculez dans un premier temps la somme des revenus annuelle. Pour rappel, les revenus listés ci dessus sont mensuels.
somme_annuelle = 0

for rev in revenus:
    annuel = rev * 12
    somme_annuelle += annuel

print("Revenus annuels totaux :", somme_annuelle)
# On calcule la somme : 

somme_sum = revenus.sum()
somme_sum
somme = somme_sum * 12
somme

Revenus annuels totaux : 250464


250464

In [63]:
#calculez ensuite la moyenne des revenus des 10 clients

In [87]:
moyenne_annuelle = somme_annuelle / len(revenus)
print(moyenne_annuelle)
moyenne_annuelle_bis = revenus.mean() * 12
moyenne_annuelle_bis

25046.4


25046.399999999998

In [71]:
#Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel. Effectuez cette modification au sein de votre array revenus.
#reperer client
index_client = np.where(revenus == 1400)
print(index_client)


(array([6]),)


In [75]:
#ajoute 200
revenus[index_client] += 200
print(revenus[index_client])


[1600]


In [77]:
revenus

array([1800, 1500, 2200, 3000, 2172, 5000, 1600, 1200, 1100, 1300])