In [1]:
import numpy as np

In [3]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]

display(tableau)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

In [5]:
#créez un array que vous nommerez data :
data = np.array(tableau)
data

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2]])

In [15]:
#ajouter nouveau client louise = [1900, 31, 1]
louise= [1900,31,1]
data = np.vstack((data, louise))


In [17]:
revenus = data[:,0]
print(revenus)


[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300 1900]


In [19]:
data

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2],
       [1900,   31,    1]])

In [25]:
#infos de PAUl:
print("Informations de Paul :")
print(data[4, :])

Informations de Paul :
[2172   37    2]


In [37]:

print("Ses mensualités maximales sont de :", round(data[4,0]*0.35,2), "€")

Ses mensualités maximales sont de : 760.2 €
